# Generated by ChatGPT on 2026-01-13
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherCity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="weather_cities", to="admin_panel.country")),
            ],
            options={
                "ordering": ["country__name", "name"],
                "unique_together": {("country", "name")},
            },
        ),
        migrations.CreateModel(
            name="WeatherTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True)),
                ("morning_time", models.TimeField(default="10:30:00")),
                ("evening_time", models.TimeField(default="20:30:00")),
                ("summer_only_backgrounds", models.BooleanField(default=False)),
                ("gif_sunny", models.FileField(blank=True, null=True, upload_to="weatherbot/gifs/")),
                ("gif_cloudy", models.FileField(blank=True, null=True, upload_to="weatherbot/gifs/")),
                ("gif_precip", models.FileField(blank=True, null=True, upload_to="weatherbot/gifs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_morning_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_evening_sent_at", models.DateTimeField(blank=True, null=True)),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tasks", to="api.weathercity")),
            ],
        ),
        migrations.CreateModel(
            name="WeatherPublishLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("morning", "Утренний"), ("evening", "Вечерний"), ("manual", "Ручной")], max_length=16)),
                ("is_ok", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="api.weathertask")),
                ("target", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.mainentity")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherTaskTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="weather_targets", to="api.mainentity")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="targets", to="api.weathertask")),
            ],
            options={
                "unique_together": {("task", "entity")},
            },
        ),
    ]
